AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Add Employee Lambda Function using DynamoDB with two layers

Parameters:
  TableName:
    Type: String
    Default: Employees
    Description: DynamoDB table name for employee records

Globals:
  Function:
    Timeout: 10
    Runtime: python3.13
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      ContentUri: ../../commons/layers/shared
      CompatibleRuntimes:
        - python3.13

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dependencies-layer
      ContentUri: ../../commons/layers/dependencies
      CompatibleRuntimes:
        - python3.13
    Metadata:
      BuildMethod: python3.13
      BuildArchitecture: x86_64
      Requirements: ../../commons/layers/dependencies/requirements.txt


  # DynamoDB Table
  EmployeeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: employee_id
          AttributeType: S
      KeySchema:
        - AttributeName: employee_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AddEmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AddEmployeeFunction
      CodeUri: ../../add_employee_service/add_employee_lambda/src/
      Handler: handler.create_employee_handler.lambda_handler
      Layers:
        - !Ref DependenciesLayer
        - !Ref SharedLayer
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          LOG_LEVEL: INFO
      Events:
        AddEmployeeAPI:
          Type: Api
          Properties:
            Path: /employee
            Method: post
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName

Outputs:
  AddEmployeeApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/employee"
    