version = 0.1
[default.deploy.parameters]
stack_name = "add-employee-stack"
resolve_s3 = true
s3_prefix = "add-employee-stack"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "TableName=\"Employees\""
image_repositories = []
