AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Get Employee Lambda Function

Globals:
  Api:
    # Global API Gateway configurations
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'GET'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 10
    Runtime: python3.13
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  SharedLayerResource:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      ContentUri: ../../commons/layers/shared
      CompatibleRuntimes:
        - python3.13

  # Define the API Gateway
  EmployeeApiGatewayResource:
    Type: AWS::Serverless::Api
    Properties:
      Name: get-employee-api-gateway
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL

  GetEmployeeLambdaFunctionResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetEmployeeFunction
      CodeUri: ../../get_employee_service/get_employee_lambda/src/
      Handler: handler.get_employee_handler.lambda_handler
      Layers:
        - !Ref SharedLayerResource
      Environment:
        Variables:
          TABLE_NAME: !ImportValue shared-resources-stack-EmployeeTableName
          LOG_LEVEL: INFO
      Events:
        GetEmployeeAPI:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeeApiGatewayResource
            Path: /employees/{employee_id}
            Method: get
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !ImportValue shared-resources-stack-EmployeeTableArn


  # API Gateway permissions for Lambda
  GetEmployeeAPIGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt GetEmployeeLambdaFunctionResource.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EmployeeApiGatewayResource}/*/GET/employees/{employee_id}"

Outputs:
  GetEmployeeApiUrl:
    Description: API Gateway endpoint URL for Get Employee
    Value: !Sub "https://${EmployeeApiGatewayResource}.execute-api.${AWS::Region}.amazonaws.com/Prod/employees/{employee_id}"

  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref EmployeeApiGatewayResource
