AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Get All Employees Lambda Function using DynamoDB with two layers

Globals:
  Api:
    # Global API Gateway configurations
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'GET'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 10
    Runtime: python3.13
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  SharedLayerResource:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      ContentUri: ../../commons/layers/shared
      CompatibleRuntimes:
        - python3.13

  # Define the API Gateway
  EmployeeApiGatewayResource:
    Type: AWS::Serverless::Api
    Properties:
      Name: get-all-employees-api-gateway
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL

  GetAllEmployeesLambdaFunctionResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetAllEmployeesFunction
      CodeUri: ../../get_all_employees_service/get_all_employees_lambda/src/
      Handler: handler.get_all_employees_handler.lambda_handler
      Layers:
        - !Ref SharedLayerResource
      Environment:
        Variables:
          TABLE_NAME: !ImportValue shared-resources-stack-EmployeeTableName
          LOG_LEVEL: INFO
      Events:
        GetAllEmployeesAPI:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeeApiGatewayResource
            Path: /employees
            Method: get
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !ImportValue shared-resources-stack-EmployeeTableName

  # API Gateway permissions for Lambda
  GetAllEmployeesPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt GetAllEmployeesLambdaFunctionResource.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EmployeeApiGatewayResource}/*/GET/employees"

Outputs:
  GetAllEmployeesApiUrl:
    Description: API Gateway endpoint URL for Get All Employees
    Value: !Sub "https://${EmployeeApiGatewayResource}.execute-api.${AWS::Region}.amazonaws.com/Prod/employees"
  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref EmployeeApiGatewayResource