AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Update Employee Lambda Function

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 10
    Runtime: python3.13
    Architectures:
      - x86_64
    Tracing: Active

Resources:

  SharedLayerResource:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      ContentUri: ../../commons/layers/shared
      CompatibleRuntimes:
        - python3.13

  EmployeeApiGatewayResource:
    Type: AWS::Serverless::Api
    Properties:
      Name: update-employees-api-gateway
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL

  UpdateEmployeeLambdaFunctionResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UpdateEmployeeFunction
      CodeUri: ../../update_employee_service/update_employee_lambda/src/
      Handler: handler.update_employee_handler.lambda_handler
      Layers:
        - !Ref SharedLayerResource
      Environment:
        Variables:
          TABLE_NAME: !ImportValue shared-resources-stack-EmployeeTableName
          LOG_LEVEL: INFO
      Events:
        UpdateEmployeeAPI:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeeApiGatewayResource
            Path: /employees/{employee_id}
            Method: put
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !ImportValue shared-resources-stack-EmployeeTableArn

  UpdateEmployeeAPIGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt UpdateEmployeeLambdaFunctionResource.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EmployeeApiGatewayResource}/*/PUT/employees/{employee_id}"

Outputs:
  UpdateEmployeeApiUrl:
    Description: API Gateway endpoint URL for Update Employee
    Value: !Sub "https://${EmployeeApiGatewayResource}.execute-api.${AWS::Region}.amazonaws.com/Prod/employees/{employee_id}"

  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref EmployeeApiGatewayResource
