version = 0.1

[default.deploy.parameters]
stack_name = "create-employee-stack"
resolve_s3 = true
s3_prefix = "create-employee-stack"
region = "eu-north-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
