AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Delete Employee Lambda Function using DynamoDB with two layers

Globals:
  Function:
    Timeout: 10
    Runtime: python3.13
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      ContentUri: ../../commons/layers/shared
      CompatibleRuntimes:
        - python3.13

  DeleteEmployeeLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteEmployeeFunction
      CodeUri: ../../delete_employee_service/delete_employee_lambda/src/
      Handler: handler.delete_employee_handler.lambda_handler
      Layers:
        - !Ref SharedLayer
      Environment:
        Variables:
          TABLE_NAME: !ImportValue shared-resources-stack-EmployeeTableName
          LOG_LEVEL: INFO
      Events:
        DeleteEmployeeAPI:
          Type: Api
          Properties:
            Path: /employees/{employee_id}
            Method: delete
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !ImportValue shared-resources-stack-EmployeeTableName

Outputs:
  DeleteEmployeeApiUrl:
    Description: API Gateway endpoint URL for Delete Employee by employee_id
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/employees/{employee_id}"
