AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Delete Employee Lambda Function

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'DELETE'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 10
    Runtime: python3.13
    Architectures:
      - x86_64
    Tracing: Active

Resources:

  SharedLayerResource:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      ContentUri: ../../commons/layers/shared
      CompatibleRuntimes:
        - python3.13

  # Define the API Gateway
  EmployeeApiGatewayResource:
    Type: AWS::Serverless::Api
    Properties:
      Name: delete-employees-api-gateway
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      Auth:
        ApiKeyRequired: true

  DeleteEmployeeLambdaFunctionResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteEmployeeFunction
      CodeUri: ../../delete_employee_service/delete_employee_lambda/src/
      Handler: handler.delete_employee_handler.lambda_handler
      Layers:
        - !Ref SharedLayerResource
      Environment:
        Variables:
          TABLE_NAME: !ImportValue shared-resources-stack-EmployeeTableName
          LOG_LEVEL: INFO
      Events:
        DeleteEmployeeAPI:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeeApiGatewayResource
            Path: /employees/{employee_id}
            Method: delete
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:DeleteItem
              Resource: !ImportValue shared-resources-stack-EmployeeTableArn

  DeleteEmployeeAPIGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt DeleteEmployeeLambdaFunctionResource.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EmployeeApiGatewayResource}/*/DELETE/employees/{employee_id}"


  DeleteEmployeeApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - EmployeeApiGatewayResource
    Properties:
      Name: DeleteEmployeeApiKey
      Description: API Key for Delete Employee API
      Enabled: true

  EmployeeApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - EmployeeApiGatewayResource
      - DeleteEmployeeLambdaFunctionResource
    Properties:
      UsagePlanName: EmployeeApiUsagePlan
      Description: Usage plan for Employee API
      ApiStages:
        - ApiId: !Ref EmployeeApiGatewayResource
          Stage: Prod
      Quota:
        Limit: 1000
        Period: MONTH
      Throttle:
        BurstLimit: 10
        RateLimit: 5

  EmployeeApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn: EmployeeApiUsagePlan
    Properties:
      KeyId: !Ref DeleteEmployeeApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref EmployeeApiUsagePlan

Outputs:
  DeleteEmployeeApiUrl:
    Description: API Gateway endpoint URL for Delete Employee
    Value: !Sub "https://${EmployeeApiGatewayResource}.execute-api.${AWS::Region}.amazonaws.com/Prod/employees/{employee_id}"

  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref EmployeeApiGatewayResource

  ApiKey:
    Description: API Key ID
    Value: !Ref DeleteEmployeeApiKey